server:
  port: 9800
  servlet:
    context-path: /service

ldap:
  ldif_upload_path: /opt/ldap/ldif_upload_path
  cacheTTL: 600000
  serviceUrl: http://47.93.124.228:6930/service/
  tempPath: /opt/ldap/temp
  ansiblePath: /usr/bin/ansible
  strategy:
    strategy_wallpaper_upload_path: /opt/ldap/strategy_wallpaper_upload_path
    strategyPyscriptPath: /opt/ldap/strategyPyscriptPath

    sudo_account:
      account: lixingbest
      password: tswcbyy5413LX
  # 接口超时时间，单位：分钟
  session-timeout: 720
  # ldap域控服务器的前缀，用于界面中区别哪些是域控哪些是普通终端
  dc-prefix: ldap
  # ldap缓存时间
  ldap-cache-timeout: 21600000
  sudoUserPasswd: '{"example": "lixingbest,123456"}'

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: "jdbc:mysql://127.0.0.1/ldap?characterEncoding=utf-8"
          username: "root"
          password: "tswcbyy5413LX"

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
  file:
    path: logs
    max-size: 500MB
    max-history: 10
